name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [ master ]   # o main, según tu rama
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Astro
        uses: withastro/action@v2
        with:
          node-version: 20
          package-manager: pnpm@10.11.0        # pnpm@9 / yarn@1 si corresponde
          path: .

      - name: Ensure .nojekyll (avoid Jekyll ignoring _astro)
        run: touch dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4